// VueCotizador/src/components/Button.vue

<script setup>
    import { defineProps } from 'vue';
    const props = defineProps({
        operador: String
        
    })

 
</script>

<template>    
    <button
    class="h-10 w-10 flex item-center justify-center font-bold bg-lime-500 rounded-full hover:outline-none
    hover:ring-2 hover:ring-offset-2 hover:ring-lime-500 text-white text-2xl"
    @click="$emit('fn')"
    >
    {{operador}}</button>
</template>

// ReactCotizador/src/components/Button.jsx
import React from 'react'

function Button({fn, operador}) {   
  return (
    <button type='button' className='h-10 w-10 flex items-center justify-center font-bold text-white text-2xl bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500' onClick={fn}>{operador}</button>
  )
}
export default Button
